#!/bin/bash

source ~/gfort

# TODO: check if valid date

jid=`sbatch --export jobdate="2014-07-27.00" job1 | awk '{print $NF }'`
echo $jid

for job in job2 job3 job4 job5 job6 job7 job8 ; do
  jid=`sbatch --export jobdate="2014-07-27.00" --dependency=afterok:$jid $job | awk '{print $NF }'`
  echo $jid
done

for jd in 2014-07-27.06 2014-07-27.12 2014-07-27.18 2014-07-28.00 2014-07-28.06 2014-07-28.12 2014-07-28.18 2014-07-29.00; do

for job in job1 job2 job3 job4 job5 job6 job7 job8 ; do
  jid=`sbatch --export jobdate="$jd" --dependency=afterok:$jid $job | awk '{print $NF }'`
  echo $jid
done

done



