#!/bin/bash
#SBATCH --account=ERA-URBAN
#SBATCH --time=1
#SBATCH --mem-per-cpu=16000
#SBATCH --ntasks=1
#SBATCH --constraint=normalmem
#SBATCH --output=Wrfout_%j.txt
#SBATCH --error=Wrferr_%j.txt
#SBATCH --job-name=wrftest2
#SBATCH --partition=ESG_Std
#SBATCH --mail-type=ALL
#SBATCH --mail-user=r.vanharen@esciencecenter.nl

ulimit -s unlimited
source ~/gfort
#export OMP_NUM_THREADS=2
cd /home/WUR/haren009/sources/WRFV3/tools/forecast
#srun ./wrf.exe

srun ./forecast.sh wrfda updatebc_lowbc $jobdate
